// @ts-nocheck -- skip type checking
import * as docs_8 from "../content/docs/develop-guide/develop.mdx?collection=docs&hash=1747583123973"
import * as docs_7 from "../content/docs/develop-guide/develop.cn.mdx?collection=docs&hash=1747583123973"
import * as docs_6 from "../content/docs/deploy-guide/security-guide.mdx?collection=docs&hash=1747583123973"
import * as docs_5 from "../content/docs/deploy-guide/security-guide.cn.mdx?collection=docs&hash=1747583123973"
import * as docs_4 from "../content/docs/deploy-guide/find-source.mdx?collection=docs&hash=1747583123973"
import * as docs_3 from "../content/docs/deploy-guide/find-source.cn.mdx?collection=docs&hash=1747583123973"
import * as docs_2 from "../content/docs/deploy-guide/deploy.mdx?collection=docs&hash=1747583123973"
import * as docs_1 from "../content/docs/deploy-guide/deploy.cn.mdx?collection=docs&hash=1747583123973"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1747583123973"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"deploy-guide/deploy.cn.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/deploy-guide/deploy.cn.mdx"}, data: docs_1 }, { info: {"path":"deploy-guide/deploy.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/deploy-guide/deploy.mdx"}, data: docs_2 }, { info: {"path":"deploy-guide/find-source.cn.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/deploy-guide/find-source.cn.mdx"}, data: docs_3 }, { info: {"path":"deploy-guide/find-source.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/deploy-guide/find-source.mdx"}, data: docs_4 }, { info: {"path":"deploy-guide/security-guide.cn.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/deploy-guide/security-guide.cn.mdx"}, data: docs_5 }, { info: {"path":"deploy-guide/security-guide.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/deploy-guide/security-guide.mdx"}, data: docs_6 }, { info: {"path":"develop-guide/develop.cn.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/develop-guide/develop.cn.mdx"}, data: docs_7 }, { info: {"path":"develop-guide/develop.mdx","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/develop-guide/develop.mdx"}, data: docs_8 }], [{"info":{"path":"deploy-guide/meta.cn.json","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/deploy-guide/meta.cn.json"},"data":{"title":"企业服务与部署","pages":["---快速上手---","find-source","---部署指南---","deploy"],"description":"RM-01 企业部署流程","root":true,"icon":"Building"}}, {"info":{"path":"deploy-guide/meta.json","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/deploy-guide/meta.json"},"data":{"title":"Enterprise Deployment","pages":["---Quick Start---","find-source","---Deployment Guide---","deploy"],"description":"RM-01 Deployment Guide","root":true,"icon":"Building"}}, {"info":{"path":"develop-guide/meta.cn.json","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/develop-guide/meta.cn.json"},"data":{"title":"应用开发及交付","description":"RM-01 应用开发及交付流程","root":true,"icon":"Code"}}, {"info":{"path":"develop-guide/meta.json","absolutePath":"/Users/lotusxu/Desktop/rminte-docs-site/content/docs/develop-guide/meta.json"},"data":{"title":"Development Guide","description":"RM-01 Development Guide","root":true,"icon":"Code"}}])